import Head from "next/head";
import ResponsiveRow from "@/components/ResponsiveRow/ResponsiveRow";
import Text from "@/components/Text/Text";
import Select from "@/components/Select/Select";

export default function Home() {
  return (
    <>
      <Head>
        <title>UI Kit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="space-y-8">
        <button className="btn rounded-full">Press me</button>

        <ResponsiveRow>
          <div className="bg-primary h-10 flex-[2]">1</div>
          <div className="bg-secondary h-10 flex-1">2</div>
          <div className="bg-accent h-10 flex-1">2</div>
        </ResponsiveRow>

        <div>
          <Text size="xs">The quick brown fox jumps over the lazy dog.</Text>
          <Text size="sm">The quick brown fox jumps over the lazy dog.</Text>
          <Text>The quick brown fox jumps over the lazy dog.</Text>
          <Text size="lg">The quick brown fox jumps over the lazy dog.</Text>
          <Text size="xl">The quick brown fox jumps over the lazy dog.</Text>
          <Text size="2xl">The quick brown fox jumps over the lazy dog.</Text>
        </div>

        <div className="btn-group gap-4 separate-pills">
          <input type="radio" name="options" data-title="Red" className="btn" />
          <input
            type="radio"
            name="options"
            data-title="Green"
            className="btn"
          />
          <input
            type="radio"
            name="options"
            data-title="Magenta"
            className="btn"
          />
          <input
            type="radio"
            name="options"
            data-title="Onometopoea"
            className="btn"
          />
        </div>

        <div>
          <select className="select select-bordered">
            <option>Pick your favorite Simpson</option>
            <option>Homer</option>
            <option>Marge</option>
            <option>Bart</option>
            <option>Lisa</option>
            <option>Maggie</option>
          </select>
        </div>

        <div className="p-1">
          <Select
            instanceId="select"
            isClearable
            options={[
              { value: "Homer", label: "Homer" },
              { value: "Marge", label: "Marge" },
              { value: "Bart", label: "Bart" },
              { value: "Lisa", label: "Lisa" },
            ]}
            isMulti
            menuIsOpen
          />
        </div>
      </div>
    </>
  );
}
